trigger:
  branches:
    include:
      - '*'
# schedules:
# - cron: "3 12,15,17,22 * * Mon-Fri"
#   displayName: Daily build of live site
#   branches:
#     include:
#     - master
#   always: true
variables:
  - group: accom sites

stages:
# build stage: build site codebase to use for deployment
- stage: Build_Codebase
  jobs:
    - template: '.build/site-build-job.yml'
      parameters:
        name: build_live_site
        displayName: Live site (exclude drafts & future published content)
        # always build on pushes to master
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        hugo_version: 0.57.2
        hugo_config_baseUrl: $(LiveSiteBaseUrl)
        hugo_config_flags: '--minify'
        site_storage_account: $(LiveSiteAccount)
        site_storage_key: $(LiveSiteAccessKey)
        build_tag: live-site

- stage: Deploy_Codebase
  dependsOn: Build_Codebase
  jobs:
    - template: '.build/site-deploy-job.yml'
      parameters:
        name: deploy_live_site
        displayName: Live site (exclude drafts & future published content)
        # always deploy on pushes to master
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        site_storage_account: $(LiveSiteAccount)
        site_storage_key: $(LiveSiteAccessKey)
        build_tag: live-site